Feature/header
nessy126/fullstack-team-project pull request #25
Opened 2022-07-18 08:09 UTC by IronHedgehog

2022-07-18 11:19 UTC, nessy126 commented on public/index.html
> +    <noscript>You need to enable JavaScript to run this app.</noscript>
Зачем эти две строки?
<noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="modalRoot"></div>

2022-07-18 11:29 UTC, nessy126 commented on src/components/AddBookForm/AddBookForm.jsx
> +          console.log("values", values);
с консольлогами не пушим

2022-07-18 11:34 UTC, nessy126 commented on src/components/GoingToReadList/GoingToReadList.jsx
> +  const books = [
Уже давно ответ приходит с бэка, для 4 точно как....

2022-07-18 11:39 UTC, nessy126 commented on src/components/Header/Header.module.scss
> +.zaebalo {
???

2022-07-18 11:42 UTC, nessy126 commented on src/components/Header/Header.module.scss
>    font-family: Monserat;
вот тут спроси у ребят как оно мексинами пишется.
Два шрифта зачем? и какие-то шрифты у нас есть в переменных

2022-07-18 11:43 UTC, nessy126 commented on src/components/Header/Header.module.scss
> +  font-family: "Montserrat";
тоже самое

2022-07-18 11:52 UTC, nessy126 commented on src/components/LibraryModal/LibraryModal.jsx
> +    const openModal = () => {
может тут проверка на пустой массив должна быть на пустой массив? она же не в любом случае открывается

2022-07-18 13:03 UTC, nessy126 commented on src/components/LibraryModal/libraryModal.module.scss
> +  font-family: "Montserrat";
этот шрифт у нас на body по умолчанию

2022-07-18 13:05 UTC, nessy126 commented on src/components/LibraryModal/libraryModal.module.scss
> +  font-family: "Montserrat";
тоже самое, он по умолчанию

2022-07-18 13:07 UTC, nessy126 commented on src/components/MainNav/MainNav.module.scss
> +  font-family: "Montserrat";
миксины

2022-07-18 13:07 UTC, nessy126 commented on src/components/MainNav/MainNav.module.scss
> +  font-family: "Montserrat";
миксины

2022-07-18 13:10 UTC, nessy126 commented on src/components/MainNav/Modal/Modal.jsx
> +      closeModal();
я вот не помню, мы же вроде должны при закрытии модалки слушателя снимать, а при открытиии вешать, так?

2022-07-18 13:23 UTC, nessy126 requested changes
и читай дискорд
и тут комменты
Рендера книг у тебя еще нет?

2022-07-19 11:27 UTC, IronHedgehog commented on src/components/LibraryModal/LibraryModal.jsx
> +    const openModal = () => {
Модалка не открывается если  есть книги

2022-07-19 11:29 UTC, IronHedgehog commented on src/components/MainNav/Modal/Modal.jsx
> +      closeModal();
там это все написано выше

2022-07-20 08:25 UTC, nessy126 approved these changes

2022-07-20 08:26 UTC, merged