Feature tabl markup
nessy126/fullstack-team-project pull request #9
Opened 2022-07-13 22:19 UTC by OlenaPatlata

I made the tabl including list of books wich user going to read. 
Also I made two calendars, but styles need to rework.

2022-07-13 23:01 UTC, nessy126 commented on src/components/TrainingData/TrainingData.jsx
> +  statistics: [{
эту статистику уже надо удалить отсюда, она в тренинге будет

2022-07-13 23:07 UTC, nessy126 requested changes
Вынеси пожалуйста компонент Table в отдельную папку, и назови файлі одинаково со стилями
И скажи, чем отличается books от booklist?

2022-07-14 06:29 UTC, OlenaPatlata commented on src/components/TrainingData/TrainingData.jsx
> +  statistics: [{
Да, это для тренировки из первоначальной модели, эти поля по статистике я не использовала

2022-07-14 10:51 UTC, nessy126 approved these changes
не забывай использовать Притер) я тоже, кстати))

2022-07-14 10:51 UTC, merged